// Emits the LOCKED circomlib Poseidon(t=2) constants for BN254, in the exact
// shape the Stellar host `poseidon_permutation` consumes, plus a Rust include
// for the mint_guard contract. Run: npm run poseidon:constants
//
// Source of truth: circomlibjs/src/poseidon_constants.json (C, M for t..=17).
// We take index 0 => t=2. C[0] is flat length (rounds_f+rounds_p)*t = 128; we
// reshape into 64 rows of 2. M[0] is the 2x2 MDS (identical to the matrix in
// the Stellar v25_poseidon migration guide).

import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const buildDir = join(root, "build");

const raw = JSON.parse(
  readFileSync(
    join(root, "node_modules/circomlibjs/src/poseidon_constants.json"),
    "utf8"
  )
);

const t = 2;
const d = 5;
const roundsF = 8;
const roundsP = 56; // N_ROUNDS_P[t-2] for t=2
const nRounds = roundsF + roundsP; // 64

const Cflat = raw.C[0]; // length 128 hex strings
if (Cflat.length !== nRounds * t) {
  throw new Error(`C[0] len ${Cflat.length} != ${nRounds * t}`);
}
// reshape to [nRounds][t]
const C_rounds = [];
for (let r = 0; r < nRounds; r++) {
  C_rounds.push([Cflat[r * t + 0], Cflat[r * t + 1]]);
}
const M = raw.M[0]; // [[..,..],[..,..]]

const BASE_2_248 = (1n << 248n).toString();
const constants = {
  field: "BN254",
  t,
  d,
  roundsF,
  roundsP,
  M,
  C_rounds,
  serialization: {
    LIMB_BYTES: 31,
    BASE: BASE_2_248, // 2^248
    MSGID_BYTES: 128,
    DOMAIN_BYTES: 62,
  },
};

function emit() {
mkdirSync(buildDir, { recursive: true });
writeFileSync(
  join(buildDir, "poseidon_t2_constants.json"),
  JSON.stringify(constants, null, 2)
);

// ---- Rust include for the contract ----
const hexToRustU256 = (h) => `\"${h}\"`; // contract parses hex -> U256 at init
const rsLines = [];
rsLines.push("// AUTO-GENERATED by circuits/scripts/gen_poseidon_constants.js");
rsLines.push("// LOCKED circomlib Poseidon(t=2) BN254 constants. Do not edit by hand.");
rsLines.push(`pub const POSEIDON_T: u32 = ${t};`);
rsLines.push(`pub const POSEIDON_D: u32 = ${d};`);
rsLines.push(`pub const POSEIDON_ROUNDS_F: u32 = ${roundsF};`);
rsLines.push(`pub const POSEIDON_ROUNDS_P: u32 = ${roundsP};`);
rsLines.push("// MDS 2x2 (hex, big-endian U256)");
rsLines.push(
  `pub const POSEIDON_MDS: [[&str; 2]; 2] = [[${hexToRustU256(M[0][0])}, ${hexToRustU256(
    M[0][1]
  )}], [${hexToRustU256(M[1][0])}, ${hexToRustU256(M[1][1])}]];`
);
rsLines.push("// Round constants: 64 rounds x 2 (hex, big-endian U256)");
rsLines.push("pub const POSEIDON_RC: [[&str; 2]; 64] = [");
for (const row of C_rounds) {
  rsLines.push(`    [${hexToRustU256(row[0])}, ${hexToRustU256(row[1])}],`);
}
rsLines.push("];");
rsLines.push(`pub const SERIALIZE_LIMB_BYTES: usize = 31;`);
rsLines.push(`pub const SERIALIZE_MSGID_BYTES: usize = 128;`);
rsLines.push(`pub const SERIALIZE_DOMAIN_BYTES: usize = 62;`);
rsLines.push("// BASE = 2^248 as big-endian 32-byte; used for limb folding");
writeFileSync(join(buildDir, "poseidon_t2_constants.rs"), rsLines.join("\n") + "\n");

console.log("[poseidon:constants] wrote:");
console.log("  build/poseidon_t2_constants.json");
console.log("  build/poseidon_t2_constants.rs");
console.log(`  t=${t} d=${d} rounds_f=${roundsF} rounds_p=${roundsP} nRounds=${nRounds}`);
console.log(`  MDS[0][0]=${M[0][0]}`);
}

// Re-export for poseidon_ref.js (side-effect-free import)
export default { t, d, roundsF, roundsP, M, C_rounds };

// Only write files when run directly: `node scripts/gen_poseidon_constants.js`
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  emit();
}
