// Generate Rust test fixtures (contracts/mint_guard/src/fixtures.rs) from the
// real proof + vkey + public signals. Single source of truth — no hand-copying
// of hex/decimal into Rust (which is the #1 source of encoding bugs).
//
// Emits byte arrays already in Stellar BN254 encoding:
//   G1 = be(X)||be(Y)                         (64 bytes)
//   G2 = be(X_c1)||be(X_c0)||be(Y_c1)||be(Y_c0) (128 bytes, EIP-197 swap)
// and public signals as 32-byte big-endian U256 words.

import { readFileSync, writeFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const buildDir = join(__dirname, "..", "build");
const outPath = join(__dirname, "..", "..", "contracts", "mint_guard", "src", "fixtures.rs");

const proof = JSON.parse(readFileSync(join(buildDir, "proof.json"), "utf8"));
const vkey = JSON.parse(readFileSync(join(buildDir, "vkey_soroban.json"), "utf8"));
const pub = JSON.parse(readFileSync(join(buildDir, "public.json"), "utf8"));

const to32BE = (dec) => {
  let x = BigInt(dec);
  const b = new Uint8Array(32);
  for (let i = 31; i >= 0; i--) { b[i] = Number(x & 0xffn); x >>= 8n; }
  return b;
};
const cat = (...a) => { const o = []; for (const x of a) o.push(...x); return Uint8Array.from(o); };
const hexToBytes = (h) => {
  const s = h.startsWith("0x") ? h.slice(2) : h;
  const o = new Uint8Array(s.length / 2);
  for (let i = 0; i < o.length; i++) o[i] = parseInt(s.substr(i * 2, 2), 16);
  return o;
};

// proof G1 [x,y,1] -> 64B ; proof G2 [[xc0,xc1],[yc0,yc1],[1,0]] -> swap 128B
const pg1 = (p) => cat(to32BE(p[0]), to32BE(p[1]));
const pg2 = (p) => cat(to32BE(p[0][1]), to32BE(p[0][0]), to32BE(p[1][1]), to32BE(p[1][0]));

const rustArr = (u8) => `[${Array.from(u8).join(", ")}]`;

const a = pg1(proof.pi_a);
const b = pg2(proof.pi_b);
const c = pg1(proof.pi_c);

let out = `// AUTO-GENERATED by circuits/scripts/gen_contract_fixtures.js — DO NOT EDIT.
// Real Groth16 proof + verification key + public journal from reserve.circom.
#![allow(clippy::all)]

pub const PROOF_A: [u8; 64] = ${rustArr(a)};
pub const PROOF_B: [u8; 128] = ${rustArr(b)};
pub const PROOF_C: [u8; 64] = ${rustArr(c)};

pub const VK_ALPHA: [u8; 64] = ${rustArr(hexToBytes(vkey.alpha))};
pub const VK_BETA: [u8; 128] = ${rustArr(hexToBytes(vkey.beta))};
pub const VK_GAMMA: [u8; 128] = ${rustArr(hexToBytes(vkey.gamma))};
pub const VK_DELTA: [u8; 128] = ${rustArr(hexToBytes(vkey.delta))};

`;

out += `pub const VK_IC: [[u8; 64]; ${vkey.ic.length}] = [\n`;
for (const p of vkey.ic) out += `    ${rustArr(hexToBytes(p))},\n`;
out += `];\n\n`;

// public signals as 32B BE words
out += `pub const PUBLIC_SIGNALS: [[u8; 32]; ${pub.length}] = [\n`;
for (const s of pub) out += `    ${rustArr(to32BE(s))},\n`;
out += `];\n`;

writeFileSync(outPath, out);
console.log(`[fixtures] wrote ${outPath}`);
console.log(`  proof A/B/C, vkey (alpha/beta/gamma/delta + ${vkey.ic.length} IC), ${pub.length} public signals`);
